[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on   = "o"
run  = "plugin open-with-cmd --args=block"
desc = "Open with command in the terminal"

[[mgr.prepend_keymap]]
on   = "O"
run  = "plugin open-with-cmd"
desc = "Open with command"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"
