[flavor]
dark = "catppuccin-mocha"

[spot]
# Section header style.
# Example: Video, Text, Image,... with green color in preview images above
title = { fg = "green" }

# Value style. Currently only support nightly.
# Example: Format: FLAC with blue color in preview images above
tbl_col = { fg = "#94e2d5" }
