[mgr]
linemode = "size"
ratio = [1, 2, 5]

[plugin]
  prepend_previewers = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo" },
    { url = "*.md", run = 'faster-piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
    { url = "*.svg", run = "resvg" },
    { url = "*.csv", run = "duckdb" },  
    { url = "*.tsv", run = "duckdb" },  
    { url = "*.parquet", run = "duckdb" },  
  ]
  prepend_preloaders = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
    { url = "*.csv", run = "duckdb", multi = false },
    { url = "*.tsv", run = "duckdb", multi = false },
    { url = "*.parquet", run = "duckdb", multi = false },
    { url = "*.db", run = "duckdb" },
    { url = "*.duckdb", run = "duckdb" },
  ]
  # There are more extensions which are supported by mediainfo.
  # Just add file's MIME type to `previewers`, `preloaders` above.
  # https://mediaarea.net/en/MediaInfo/Support/Formats

