git:
  parseEmoji: true
customCommands:
  - command: 'git commit -m "{{ .Form.emoji }} {{ .Form.message }}"' 
    context: files
    description: Commit changes using gitmojis
    key: C
    prompts:
      - command: gitmoji -l
        filter: ^(.*?) - (:.*?:) - (.*)$
        key: emoji
        labelFormat: '{{ .group_1 }} - {{ .group_3 }}'
        title: 'Select a gitmoji:'
        type: menuFromCommand
        valueFormat: '{{ .group_2 }}'
      - key: message
        title: 'Enter a commit message:'
        type: input
